In [4]:
import numpy as np

# Create NumPy Array Using Function
<h3>This is the way to give heading</h3>

In [7]:
#zeros, #ones, #eye, #diag, #randint, #rand, #randn

In [15]:
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
arr = np.ones((3,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
arr = np.eye((5))
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
arr1 = np.eye(4,4)
arr1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
arr = np.diag([1,2,3,4,5])
arr

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [34]:
#it will give you random integer numbers
rand_arr = np.random.randint(1,15,4) #(low, high, number of int you want)
rand_arr

array([ 5,  6,  3, 13])

In [35]:
#it will provide random numbers
rand_arr = np.random.rand(2,3)
rand_arr

array([[0.75384156, 0.99457468, 0.23022108],
       [0.34575534, 0.29976454, 0.49592582]])

In [42]:
rand_arr = np.random.randn(5)
rand_arr

array([ 0.20276569,  0.67616373, -0.11062322,  0.57656795,  1.59385582])